services:
  - type: web
    name: miprimeraweb-proxy
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20
